### ISSUE TITLE
Wrong values every 16th time 

### ISSUE THREAD

**Issue by fred9999** [sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library#9]
Hi,

I bought a couple of SparkFun ISM330DHCX + MMC5983MA modules. Really accurate sensors, thank you.

Testing MMC5983MA with your library I encountered a strange problem though. Running the example Example1-I2C_Simple_measurement.ino I get wrong measurements in every 16th time the measurement is taken. It does not depend on the delay number at the end of the loop. With delay bigger or smaller, the wrong measurement occurs every 16th time.

When using the call
currentX = myMag.getMeasurementX();
currentY = myMag.getMeasurementY();
currentZ = myMag.getMeasurementZ();
all axes have wrong measurements

When using the call
myMag.getMeasurementXYZ(&currentX, &currentY, &currentZ);
only X axis has wrong measurements

For clarity I have added screenshots of Arduino serial plotter view.

I am using the 1.0.3 version of the library and I am running the code on ESP32.

Hopefully you can solve this problem.

Thank you beforehand,
Fred

![problem_X_axis](https://user-images.githubusercontent.com/47754700/216833185-f458d77d-5cc8-4a53-81e9-06d3eae72ffc.jpg)
![problem_all_axes](https://user-images.githubusercontent.com/47754700/216833193-bd8da7ad-6e9b-440a-83da-4069820506b8.jpg)

**Comment by PaulZC** [comment]
Hi @fred9999 ,

Thanks for reporting this issue. I'm seeing the same thing:

![image](https://user-images.githubusercontent.com/5690545/217320788-0a4e4815-8e5e-4d30-8dfe-b39b6f450f80.png)

Curiously, it seems limited to the discrete reads with ```getMeasurement```. The smooth data to the left was taken using continuous mode. The spiky data to the right is taken with discrete reads.

Investigating!

Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi @fred9999 ,

OK. Solved!

![image](https://user-images.githubusercontent.com/5690545/217517738-f2702cc6-0b46-4d97-bbbc-b3595124be4f.png)


This was a very subtle issue... In the code, we were doing a read-modify-write when setting the TM_M bit in INT_CTRL_0_REG to start the conversion. According to the datasheet, that should have been fine as the other bits should all have been reading as zero. Except, they weren't. The register actually reads as 0x61: the OTP_Read, Auto_SR_en and TM_M bits read as '1'. This means we were putting the chip into Auto-Set-Reset mode every time. The spikes in the data were caused by the periodic set-resets...

I will be releasing version 1.1.0 shortly. Please update and the spikes will magically go away... ;-)

Thanks again for reporting,
Paul

**Comment by PaulZC** [comment]
Just for fun, here's what the "ExtraCurrent" settings do to the data:

![image](https://user-images.githubusercontent.com/5690545/217528261-275d5a19-01e5-4044-8415-c14e53df7c72.png)


If you want to try this at home, add the following into ```loop```:

```
    static int loopCount = 0;
    
    if (loopCount % 100 == 0)
      myMag.applyExtraCurrentPosToNeg();
    else if (loopCount % 100 == 25)
      myMag.removeExtraCurrentPosToNeg();
    else if (loopCount % 100 == 50)
      myMag.applyExtracurrentNegToPos();
    else if (loopCount % 100 == 75)
      myMag.removeExtracurrentNegToPos();

    loopCount++;
```

**Comment by fred9999** [comment]
Wonderful! 

Thank you Paul for quick action. The library is working properly now on my side also.

Kind regards,
Fred
